"""
Sports reporting and persona chat.
"""

import json
import os
import threading
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional

from ..models.sports_workspace import SPORTS_WORKSPACE_CONTRACT_VERSION, SportsWorkspaceManager, SportsWorkspaceStatus
from ..models.task import TaskManager, TaskStatus
from ..utils.llm_client import LLMClient
from ..utils.logger import get_logger
from .sports_simulator import SportsSimulationService, SportsSimulationStatus

logger = get_logger("hermes.sports_reporter")


class SportsReportService:
    """Generate sports reports and handle postgame persona chat."""

    def __init__(self):
        self.task_manager = TaskManager()
        self.simulator = SportsSimulationService()
        self.llm_client = None
        self.llm_error = None
        try:
            self.llm_client = LLMClient()
        except Exception as exc:
            self.llm_error = str(exc)

    def generate_report_async(self, workspace_id: str) -> Dict[str, str]:
        workspace = SportsWorkspaceManager.get_workspace(workspace_id)
        if not workspace or not workspace.latest_simulation_id:
            raise ValueError("Workspace does not have a completed simulation")
        if workspace.contract_version < SPORTS_WORKSPACE_CONTRACT_VERSION:
            raise ValueError("Workspace was generated by an older fallback-based planner. Re-plan the matchup before generating reports.")
        if not self.llm_client:
            raise RuntimeError(f"Report generation requires a configured LLM client: {self.llm_error or 'unknown error'}")
        state = self.simulator.get_state(workspace_id, workspace.latest_simulation_id)
        if not state or state.status != SportsSimulationStatus.COMPLETED:
            raise ValueError("Report generation requires a completed simulation")

        task_id = self.task_manager.create_task(
            task_type="sports_report",
            metadata={"workspace_id": workspace_id, "simulation_id": workspace.latest_simulation_id},
        )
        report_id = f"report_{uuid.uuid4().hex[:12]}"
        workspace.latest_report_task_id = task_id
        workspace.latest_report_id = report_id
        SportsWorkspaceManager.save_workspace(workspace)

        thread = threading.Thread(target=self._report_worker, args=(workspace_id, report_id, task_id), daemon=True)
        thread.start()
        return {"report_id": report_id, "task_id": task_id}

    def _report_worker(self, workspace_id: str, report_id: str, task_id: str) -> None:
        workspace = SportsWorkspaceManager.get_workspace(workspace_id)
        if not workspace or not workspace.latest_simulation_id:
            self.task_manager.fail_task(task_id, "Workspace does not have a completed simulation")
            return

        self.task_manager.update_task(task_id, status=TaskStatus.PROCESSING, progress=10, message="Building sports report")
        try:
            state = self.simulator.get_state(workspace_id, workspace.latest_simulation_id)
            events = self.simulator.get_events(workspace_id, workspace.latest_simulation_id)
            if not state or state.status != SportsSimulationStatus.COMPLETED:
                raise ValueError("Simulation is not complete yet")

            report_markdown = self._build_report_markdown(workspace, state.to_dict(), events)
            report_path = os.path.join(SportsWorkspaceManager.get_reports_dir(workspace_id), f"{report_id}.md")
            os.makedirs(os.path.dirname(report_path), exist_ok=True)
            with open(report_path, "w", encoding="utf-8") as f:
                f.write(report_markdown)

            workspace.status = SportsWorkspaceStatus.REPORT_READY
            workspace.error = None
            SportsWorkspaceManager.save_workspace(workspace)
            self.task_manager.complete_task(
                task_id,
                {"report_id": report_id, "workspace_id": workspace_id, "path": report_path},
            )
        except Exception as exc:
            logger.exception("Sports report generation failed")
            if workspace:
                workspace.error = str(exc)
                SportsWorkspaceManager.save_workspace(workspace)
            self.task_manager.fail_task(task_id, str(exc))

    def get_report(self, workspace_id: str, report_id: Optional[str] = None) -> Optional[Dict[str, Any]]:
        workspace = SportsWorkspaceManager.get_workspace(workspace_id)
        if not workspace:
            return None
        report_id = report_id or workspace.latest_report_id
        if not report_id:
            return None
        report_path = os.path.join(SportsWorkspaceManager.get_reports_dir(workspace_id), f"{report_id}.md")
        if not os.path.exists(report_path):
            return None
        with open(report_path, "r", encoding="utf-8") as f:
            content = f.read()
        return {"report_id": report_id, "content": content}

    def chat(
        self,
        workspace_id: str,
        persona_name: str,
        message: str,
        chat_history: Optional[List[Dict[str, str]]] = None,
    ) -> Dict[str, Any]:
        workspace = SportsWorkspaceManager.get_workspace(workspace_id)
        if not workspace or not workspace.latest_simulation_id:
            raise ValueError("Workspace does not have simulation context")
        if workspace.contract_version < SPORTS_WORKSPACE_CONTRACT_VERSION:
            raise ValueError("Workspace was generated by an older fallback-based planner. Re-plan the matchup before using persona chat.")
        state = self.simulator.get_state(workspace_id, workspace.latest_simulation_id)
        events = self.simulator.get_events(workspace_id, workspace.latest_simulation_id)
        if not state:
            raise ValueError("Simulation state not found")
        if not self.llm_client:
            raise RuntimeError(f"Persona chat requires a configured LLM client: {self.llm_error or 'unknown error'}")

        persona_content = self._load_persona_content(workspace, persona_name)
        history_lines = []
        for turn in chat_history or []:
            history_lines.append(f"{turn.get('role', 'user')}: {turn.get('content', '')}")
        recent_events = "\n".join(f"- {event['play_by_play']}" for event in events[-8:])
        digest = self._simulation_digest(state.to_dict(), events)
        participant_profile = self._participant_profile(workspace, persona_name)

        reply = self.llm_client.chat(
            messages=[
                {
                    "role": "system",
                    "content": (
                        f"You are {persona_name} responding after a simulated sports match. "
                        "Use the supplied dossier, structured persona profile, and match history. "
                        "Stay grounded in the simulation and speak from the role's perspective."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"Persona dossier:\n{persona_content}\n\n"
                        f"Persona profile:\n{json.dumps(participant_profile, ensure_ascii=False, indent=2) if participant_profile else 'Match analyst view'}\n\n"
                        f"Match state:\n{state.to_dict()}\n\n"
                        f"Match digest:\n{json.dumps(digest, ensure_ascii=False, indent=2)}\n\n"
                        f"Recent match events:\n{recent_events}\n\n"
                        f"Chat history:\n{os.linesep.join(history_lines) if history_lines else 'No history'}\n\n"
                        f"User message: {message}"
                    ),
                },
            ],
            temperature=0.5,
            max_tokens=500,
        )

        return {
            "persona": persona_name,
            "reply": reply,
            "generated_at": datetime.now().isoformat(),
        }

    def _build_report_markdown(self, workspace, state: Dict[str, Any], events: List[Dict[str, Any]]) -> str:
        if not self.llm_client:
            raise RuntimeError("Report generation requires a configured LLM client")
        digest = self._simulation_digest(state, events)
        key_events = self._key_events(events)
        return self.llm_client.chat(
            messages=[
                {
                    "role": "system",
                    "content": (
                        "Write a concise basketball postgame report in Markdown with sections: Final Score, "
                        "Key Turning Points, Coaching Read, Player Spotlight, Scenario Effects, Phase Notes."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"Workspace summary: {workspace.matchup_summary}\n"
                        f"Scenario: {workspace.scenario.to_dict()}\n"
                        f"Simulation state: {state}\n"
                        f"Simulation digest: {json.dumps(digest, ensure_ascii=False)}\n"
                        f"Key structured events: {json.dumps(key_events, ensure_ascii=False)}"
                    ),
                },
            ],
            temperature=0.4,
            max_tokens=900,
        )

    def _load_persona_content(self, workspace, persona_name: str) -> str:
        if persona_name.lower() == "match analyst":
            return workspace.matchup_summary
        participant = next((item for item in workspace.participants if item["name"] == persona_name), None)
        if not participant:
            raise ValueError(f"Persona '{persona_name}' does not exist in this workspace")
        if not participant.get("path") or not os.path.exists(participant["path"]):
            raise ValueError(f"Persona dossier is missing for '{persona_name}'")
        with open(participant["path"], "r", encoding="utf-8") as f:
            return f.read()

    def _participant_profile(self, workspace, persona_name: str) -> Optional[Dict[str, Any]]:
        if persona_name.lower() == "match analyst":
            return None
        participant = next((item for item in workspace.participants if item["name"] == persona_name), None)
        if not participant:
            return None
        return participant.get("profile")

    def _simulation_digest(self, state: Dict[str, Any], events: List[Dict[str, Any]]) -> Dict[str, Any]:
        scoring: Dict[str, int] = {}
        turnovers = {"home": 0, "away": 0}
        fouls = 0
        offensive_rebounds = 0
        phase_counts: Dict[str, int] = {}

        for event in events:
            actor = str(event.get("actor") or event.get("primary_actor") or "").strip()
            points = int(event.get("points") or 0)
            if actor and points > 0:
                scoring[actor] = scoring.get(actor, 0) + points
            if event.get("action_type") == "turnover":
                turnovers[str(event.get("offense_team") or "home")] = turnovers.get(str(event.get("offense_team") or "home"), 0) + 1
            if event.get("foul_type"):
                fouls += 1
            if event.get("rebound_type") == "offensive":
                offensive_rebounds += 1
            phase = str(event.get("phase") or "").strip()
            if phase:
                phase_counts[phase] = phase_counts.get(phase, 0) + 1

        top_scorers = [
            {"name": name, "points": points}
            for name, points in sorted(scoring.items(), key=lambda item: item[1], reverse=True)[:5]
        ]
        return {
            "final_score": f"{state.get('home_team', '')} {state.get('home_score', 0)} - {state.get('away_score', 0)} {state.get('away_team', '')}",
            "simulation_mode": state.get("simulation_mode"),
            "quarter": state.get("quarter"),
            "overtime": state.get("overtime"),
            "team_fouls": {
                "home": state.get("home_team_fouls", 0),
                "away": state.get("away_team_fouls", 0),
            },
            "timeouts": {
                "home": state.get("home_timeouts", 0),
                "away": state.get("away_timeouts", 0),
            },
            "turnovers": turnovers,
            "fouls_whistled": fouls,
            "offensive_rebounds": offensive_rebounds,
            "top_scorers": top_scorers,
            "phase_counts": phase_counts,
        }

    def _key_events(self, events: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        filtered = [
            event for event in events
            if int(event.get("points") or 0) > 0
            or event.get("action_type") in {"turnover", "foul", "timeout", "substitution"}
            or event.get("rebound_type") == "offensive"
        ]
        trimmed = []
        for event in filtered[-40:]:
            trimmed.append({
                "segment": event.get("segment"),
                "clock": event.get("clock"),
                "phase": event.get("phase"),
                "action_type": event.get("action_type"),
                "actor": event.get("actor") or event.get("primary_actor"),
                "target": event.get("target") or event.get("secondary_actor"),
                "defender": event.get("defender"),
                "points": event.get("points", 0),
                "outcome": event.get("outcome"),
                "play_by_play": event.get("play_by_play"),
            })
        return trimmed
